global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'uptime-monitor'
    static_configs:
      - targets: ['uptime-prometheus-exporter:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093